services:
  # ------------------
  # The Backend Server
  # ------------------
  - type: web
    name: magnetic-mayhem-server
    env: docker
    repo: https://github.com/AzzouzAimen/magnetic-mayhem
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    healthCheckPath: /health
    plan: free
    envVars:
      - key: PORT
        value: 4001
      - key: CLIENT_URL
        fromService:
          type: web
          name: magnetic-mayhem-client # The service to get the value from
          envVarKey: RENDER_EXTERNAL_URL # The specific key Render provides for the public URL

  # --------------------
  # The Frontend Client
  # --------------------
  - type: web
    name: magnetic-mayhem-client
    env: docker
    repo: https://github.com/AzzouzAimen/magnetic-mayhem
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    plan: free
    http:
      port: 80
    # Create the .env.production file before building
    buildCommand: 'echo "VITE_API_URL=$VITE_API_URL" > .env.production && docker build -t $RENDER_IMAGE_NAME .'
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: magnetic-mayhem-server
          envVarKey: RENDER_EXTERNAL_URL