services:
  # ------------------
  # The Backend Server
  # ------------------
  - type: web
    name: magnetic-mayhem-server
    env: docker
    repo: https://github.com/AzzouzAimen/magnetic-mayhem
    dockerfilePath: ./server/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 4001
      # --- MODIFICATION ---
      # We construct the client's URL manually
      - key: CLIENT_URL
        # This tells Render not to automatically restart the server if the client's URL changes
        # which is the correct behavior for this kind of reference.
        sync: false
        value: https://${magnetic-mayhem-client.host}

  # --------------------
  # The Frontend Client
  # --------------------
  - type: web
    name: magnetic-mayhem-client
    env: docker
    repo: https://github.com/AzzouzAimen/magnetic-mayhem
    dockerfilePath: ./client/Dockerfile
    envVars:
      # --- MODIFICATION ---
      # We construct the server's URL manually
      - key: VITE_API_URL
        sync: false
        value: https://${magnetic-mayhem-server.host}