services:
  - type: web
    name: magnetic-mayhem-server
    env: docker
    repo: https://github.com/AzzouzAimen/magnetic-mayhem
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    healthCheckPath: /health
    plan: free
    envVars:
      - key: PORT
        value: 4001
      - key: CLIENT_URL
        value: https://${magnetic-mayhem-client.host}

  - type: web
    name: magnetic-mayhem-client
    env: docker
    repo: https://github.com/AzzouzAimen/magnetic-mayhem
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    plan: free
    http:
      port: 80 # Explicitly tell Render that Nginx listens on port 80
    envVars:
      - key: VITE_API_URL
        value: https://${magnetic-mayhem-server.host} # Construct the URL from the server's host