services:
  # ------------------
  # The Backend Server
  # ------------------
  - type: web
    name: magnetic-mayhem-server
    env: docker
    repo: https://github.com/AzzouzAimen/magnetic-mayhem
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    healthCheckPath: /health
    plan: free
    envVars:
      - key: PORT
        value: 4001
      - key: CLIENT_URL
        value: https://${magnetic-mayhem-client.host}

  # --------------------
  # The Frontend Client
  # --------------------
  - type: web
    name: magnetic-mayhem-client
    env: docker
    repo: https://github.com/AzzouzAimen/magnetic-mayhem
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    plan: free
    http:
      port: 80
    # --- THIS IS THE KEY TO THE SOLUTION ---
    buildCommand: | # The '|' allows for a multi-line shell script
      echo "VITE_API_URL=${magnetic-mayhem-server.host}" > .env.production
      docker build -t $RENDER_IMAGE_NAME .