services:
  # ------------------
  # The Backend Server
  # ------------------
  - type: web
    name: magnetic-mayhem-server
    env: docker
    repo: https://github.com/AzzouzAimen/magnetic-mayhem 
    dockerfilePath: ./server/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 4001
      - key: CLIENT_URL
        fromService:
          type: web
          name: magnetic-mayhem-client
          property: url

  # --------------------
  # The Frontend Client
  # --------------------
  - type: web
    name: magnetic-mayhem-client
    env: docker
    repo: https://github.com/AzzouzAimen/magnetic-mayhem 
    dockerfilePath: ./client/Dockerfile
    # --- THIS BLOCK IS NEW AND REPLACES dockerBuildCommand ---
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: magnetic-mayhem-server
          property: url