services:
  # ------------------
  # The Backend Server
  # ------------------
  - type: web
    name: magnetic-mayhem-server
    env: docker
    repo: https://github.com/AzzouzAimen/magnetic-mayhem
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 4001
      - key: CLIENT_URL
        value: https://${magnetic-mayhem-client.host}
  # --------------------
  # The Frontend Client
  # --------------------
  - type: web
    name: magnetic-mayhem-client
    env: docker
    repo: https://github.com/AzzouzAimen/magnetic-mayhem
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    envVars:
      - key: VITE_API_URL
        value: https://${magnetic-mayhem-server.host}